# Generated by Django 5.0.7 on 2024-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro',
            name='category',
            field=models.CharField(choices=[('frutas', 'Frutas'), ('semillas', 'Semillas'), ('vegetales', 'Vegetales')], default='frutas', max_length=10),
            preserve_default=False,
        ),
    ]
